# Generated by Django 4.2.6 on 2023-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_custom_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='custom_groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='custom_permissions',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscribers',
            field=models.IntegerField(),
        ),
    ]
