# Generated by Django 4.2.6 on 2023-11-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
